; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p:32:32-i64:64-n32:64-S128"
target triple = "wasm32-unknown-unknown"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

define i32 @Answer() {
entry:
  %Answer.ret = alloca i32
  store i32 0, ptr %Answer.ret
  store i32 42, ptr %Answer.ret
  %t1 = load i32, ptr %Answer.ret
  ret i32 %t1
}

define i32 @main() {
entry:
  ret i32 0
}
