; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

@v = global i32 0
@x = global i32 0

define i32 @main() {
entry:
  %t1 = add nsw i32 3, 4
  store i32 %t1, ptr @x
  br label %seq_1
seq_1:
  %t2 = load i32, ptr @x
  %t3 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t3, i32 %t2)
  br label %seq_2
seq_2:
  %t4 = mul nsw i32 10, 5
  store i32 %t4, ptr @x
  br label %seq_3
seq_3:
  %t5 = load i32, ptr @x
  %t6 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t6, i32 %t5)
  br label %seq_4
seq_4:
  %t7 = add nsw i32 10, 11
  %t8 = mul nsw i32 2, %t7
  store i32 %t8, ptr @x
  br label %seq_5
seq_5:
  %t9 = load i32, ptr @x
  %t10 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t10, i32 %t9)
  br label %seq_6
seq_6:
  store i32 1, ptr @v
  br label %seq_7
seq_7:
  %t11 = load i32, ptr @v
  %t12 = mul nsw i32 2, 3
  %t13 = add nsw i32 %t11, %t12
  store i32 %t13, ptr @x
  br label %seq_8
seq_8:
  %t14 = load i32, ptr @x
  %t15 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t15, i32 %t14)
  ret i32 0
}
