; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [21 x i8] c"x is greater than 10\00"
@.str.1 = private unnamed_addr constant [16 x i8] c"x is 10 or less\00"
@.str.2 = private unnamed_addr constant [8 x i8] c"x is 20\00"
@.str.3 = private unnamed_addr constant [12 x i8] c"x is not 20\00"

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

@x = global i32 0

define i32 @main() {
entry:
  store i32 15, ptr @x
  br label %seq_1
seq_1:
  %t1 = load i32, ptr @x
  %t2 = icmp sgt i32 %t1, 10
  %t3 = zext i1 %t2 to i32
  %t4 = icmp ne i32 %t3, 0
  br i1 %t4, label %if_then_2, label %if_else_3
if_then_2:
  %t5 = getelementptr inbounds [21 x i8], ptr @.str.0, i32 0, i32 0
  %t6 = getelementptr inbounds [4 x i8], ptr @.fmt_strln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t6, ptr %t5)
  br label %if_end_4
if_else_3:
  %t7 = getelementptr inbounds [16 x i8], ptr @.str.1, i32 0, i32 0
  %t8 = getelementptr inbounds [4 x i8], ptr @.fmt_strln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t8, ptr %t7)
  br label %if_end_4
if_end_4:
  br label %seq_5
seq_5:
  %t9 = load i32, ptr @x
  %t10 = icmp eq i32 %t9, 20
  %t11 = zext i1 %t10 to i32
  %t12 = icmp ne i32 %t11, 0
  br i1 %t12, label %if_then_6, label %if_else_7
if_then_6:
  %t13 = getelementptr inbounds [8 x i8], ptr @.str.2, i32 0, i32 0
  %t14 = getelementptr inbounds [4 x i8], ptr @.fmt_strln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t14, ptr %t13)
  br label %if_end_8
if_else_7:
  %t15 = getelementptr inbounds [12 x i8], ptr @.str.3, i32 0, i32 0
  %t16 = getelementptr inbounds [4 x i8], ptr @.fmt_strln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t16, ptr %t15)
  br label %if_end_8
if_end_8:
  ret i32 0
}
