; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

@i = global i32 0

define i32 @main() {
entry:
  store i32 1, ptr @i
  br label %for_hdr_1
for_hdr_1:
  %t1 = load i32, ptr @i
  %t2 = icmp sle i32 %t1, 6
  br i1 %t2, label %for_body_2, label %for_end_4
for_body_2:
  %t3 = load i32, ptr @i
  %t4 = icmp eq i32 %t3, 2
  %t5 = zext i1 %t4 to i32
  %t6 = icmp ne i32 %t5, 0
  br i1 %t6, label %if_then_5, label %if_end_7
if_then_5:
  br label %for_step_3
if_end_7:
  br label %seq_8
seq_8:
  %t7 = load i32, ptr @i
  %t8 = icmp eq i32 %t7, 4
  %t9 = zext i1 %t8 to i32
  %t10 = icmp ne i32 %t9, 0
  br i1 %t10, label %if_then_9, label %if_end_11
if_then_9:
  br label %for_step_3
if_end_11:
  br label %seq_12
seq_12:
  %t11 = load i32, ptr @i
  %t12 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t12, i32 %t11)
  br label %for_step_3
for_step_3:
  %t13 = load i32, ptr @i
  %t14 = add nsw i32 %t13, 1
  store i32 %t14, ptr @i
  br label %for_hdr_1
for_end_4:
  ret i32 0
}
