; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

define void @PrintSum(i32 %arg_0, i32 %arg_1) {
entry:
  %a.addr = alloca i32
  store i32 %arg_0, ptr %a.addr
  %b.addr = alloca i32
  store i32 %arg_1, ptr %b.addr
  %loc_s = alloca i32
  store i32 0, ptr %loc_s
  %t1 = load i32, ptr %a.addr
  %t2 = load i32, ptr %b.addr
  %t3 = add nsw i32 %t1, %t2
  store i32 %t3, ptr %loc_s
  br label %seq_1
seq_1:
  %t4 = load i32, ptr %loc_s
  %t5 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t5, i32 %t4)
  ret void
}

define i32 @main() {
entry:
  call void @PrintSum(i32 3, i32 7)
  br label %seq_1
seq_1:
  call void @PrintSum(i32 100, i32 200)
  ret i32 0
}
