; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

@result = global i32 0

define i32 @Square(i32 %arg_0) {
entry:
  %n.addr = alloca i32
  store i32 %arg_0, ptr %n.addr
  %Square.ret = alloca i32
  store i32 0, ptr %Square.ret
  %t1 = load i32, ptr %n.addr
  %t2 = load i32, ptr %n.addr
  %t3 = mul nsw i32 %t1, %t2
  store i32 %t3, ptr %Square.ret
  %t4 = load i32, ptr %Square.ret
  ret i32 %t4
}

define i32 @main() {
entry:
  %t1 = call i32 @Square(i32 7)
  store i32 %t1, ptr @result
  br label %seq_1
seq_1:
  %t2 = load i32, ptr @result
  %t3 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t3, i32 %t2)
  ret i32 0
}
