; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

@i = global i32 0

define i32 @main() {
entry:
  store i32 5, ptr @i
  br label %for_hdr_1
for_hdr_1:
  %t1 = load i32, ptr @i
  %t2 = icmp sge i32 %t1, 1
  br i1 %t2, label %for_body_2, label %for_end_4
for_body_2:
  %t3 = load i32, ptr @i
  %t4 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t4, i32 %t3)
  br label %for_step_3
for_step_3:
  %t5 = load i32, ptr @i
  %t6 = sub nsw i32 %t5, 1
  store i32 %t6, ptr @i
  br label %for_hdr_1
for_end_4:
  ret i32 0
}
