; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

@x = global i32 0

define i32 @GetX() {
entry:
  %GetX.ret = alloca i32
  store i32 0, ptr %GetX.ret
  %loc_x = alloca i32
  store i32 0, ptr %loc_x
  store i32 99, ptr %loc_x
  br label %seq_1
seq_1:
  %t1 = load i32, ptr %loc_x
  store i32 %t1, ptr %GetX.ret
  %t2 = load i32, ptr %GetX.ret
  ret i32 %t2
}

define i32 @main() {
entry:
  store i32 1, ptr @x
  br label %seq_1
seq_1:
  %t1 = call i32 @GetX()
  %t2 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t2, i32 %t1)
  br label %seq_2
seq_2:
  %t3 = load i32, ptr @x
  %t4 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t4, i32 %t3)
  ret i32 0
}
