; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

@i = global i32 0

define i32 @main() {
entry:
  store i32 0, ptr @i
  br label %seq_1
seq_1:
  br label %while_cond_2
while_cond_2:
  %t1 = load i32, ptr @i
  %t2 = icmp slt i32 %t1, 5
  %t3 = zext i1 %t2 to i32
  %t4 = icmp ne i32 %t3, 0
  br i1 %t4, label %while_body_3, label %while_end_4
while_body_3:
  %t5 = load i32, ptr @i
  %t6 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t6, i32 %t5)
  br label %seq_5
seq_5:
  %t7 = load i32, ptr @i
  %t8 = add nsw i32 %t7, 1
  store i32 %t8, ptr @i
  br label %while_cond_2
while_end_4:
  ret i32 0
}
