; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

@i = global i32 0
@j = global i32 0

define i32 @main() {
entry:
  store i32 1, ptr @i
  br label %seq_1
seq_1:
  br label %while_cond_2
while_cond_2:
  %t1 = load i32, ptr @i
  %t2 = icmp sle i32 %t1, 3
  %t3 = zext i1 %t2 to i32
  %t4 = icmp ne i32 %t3, 0
  br i1 %t4, label %while_body_3, label %while_end_4
while_body_3:
  store i32 1, ptr @j
  br label %seq_5
seq_5:
  br label %while_cond_6
while_cond_6:
  %t5 = load i32, ptr @j
  %t6 = icmp sle i32 %t5, 3
  %t7 = zext i1 %t6 to i32
  %t8 = icmp ne i32 %t7, 0
  br i1 %t8, label %while_body_7, label %while_end_8
while_body_7:
  %t9 = load i32, ptr @i
  %t10 = load i32, ptr @j
  %t11 = icmp eq i32 %t9, %t10
  %t12 = zext i1 %t11 to i32
  %t13 = icmp ne i32 %t12, 0
  br i1 %t13, label %if_then_9, label %if_end_11
if_then_9:
  %t14 = load i32, ptr @i
  %t15 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t15, i32 %t14)
  br label %if_end_11
if_end_11:
  br label %seq_12
seq_12:
  %t16 = load i32, ptr @j
  %t17 = add nsw i32 %t16, 1
  store i32 %t17, ptr @j
  br label %while_cond_6
while_end_8:
  br label %seq_13
seq_13:
  %t18 = load i32, ptr @i
  %t19 = add nsw i32 %t18, 1
  store i32 %t19, ptr @i
  br label %while_cond_2
while_end_4:
  ret i32 0
}
