; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [22 x i8] c"Hello from procedure!\00"

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

define void @SayHello() {
entry:
  %t1 = getelementptr inbounds [22 x i8], ptr @.str.0, i32 0, i32 0
  %t2 = getelementptr inbounds [4 x i8], ptr @.fmt_strln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t2, ptr %t1)
  ret void
}

define i32 @main() {
entry:
  call void @SayHello()
  ret i32 0
}
