; Generated by DelphiLite compiler
source_filename = "delphi"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(ptr noundef, ...)
declare i32 @scanf(ptr noundef, ...)

@.fmt_intln = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_strln = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_scan_int = private unnamed_addr constant [3 x i8] c"%d\00"

@result = global i32 0

define i32 @Factorial(i32 %arg_0) {
entry:
  %n.addr = alloca i32
  store i32 %arg_0, ptr %n.addr
  %Factorial.ret = alloca i32
  store i32 0, ptr %Factorial.ret
  %t1 = load i32, ptr %n.addr
  %t2 = icmp sle i32 %t1, 1
  %t3 = zext i1 %t2 to i32
  %t4 = icmp ne i32 %t3, 0
  br i1 %t4, label %if_then_1, label %if_else_2
if_then_1:
  store i32 1, ptr %Factorial.ret
  br label %if_end_3
if_else_2:
  %t5 = load i32, ptr %n.addr
  %t6 = load i32, ptr %n.addr
  %t7 = sub nsw i32 %t6, 1
  %t8 = call i32 @Factorial(i32 %t7)
  %t9 = mul nsw i32 %t5, %t8
  store i32 %t9, ptr %Factorial.ret
  br label %if_end_3
if_end_3:
  %t10 = load i32, ptr %Factorial.ret
  ret i32 %t10
}

define i32 @main() {
entry:
  %t1 = call i32 @Factorial(i32 5)
  store i32 %t1, ptr @result
  br label %seq_1
seq_1:
  %t2 = load i32, ptr @result
  %t3 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t3, i32 %t2)
  br label %seq_2
seq_2:
  %t4 = call i32 @Factorial(i32 0)
  store i32 %t4, ptr @result
  br label %seq_3
seq_3:
  %t5 = load i32, ptr @result
  %t6 = getelementptr inbounds [4 x i8], ptr @.fmt_intln, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %t6, i32 %t5)
  ret i32 0
}
